ARG __active_transfer_dcc_ibm_image=ibmwebmethods.azurecr.io/webmethods-activetransfer-dcc
ARG __active_transfer_dcc_ibm_image_tag=11.1.0.4
FROM ${__active_transfer_dcc_ibm_image}:${__active_transfer_dcc_ibm_image_tag}
