apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "active-transfer.fullname" . }}-application-properties
  labels:
    {{- include "active-transfer.labels" . | nindent 4 }}
data:
  application.properties: |
{{ .Files.Get (printf "gitops/config/%s/application.properties" .Values.envName) | indent 4 }}