{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "active-transfer.fullname" . }}-vfs
  labels:
    {{- include "active-transfer.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- if .Values.persistence.accessModes }}
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
    {{- else }}
    - {{ .Values.persistence.accessMode }}
    {{- end }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
