apiVersion: v1
kind: Service
metadata:
  name: {{ include "active-transfer.fullname" . }}
  labels:
    {{- include "active-transfer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.ports }}
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "active-transfer.selectorLabels" . | nindent 4 }}
