services:
  terraform:
    # obtain this image using
    #  https://github.com/ibm-webmethods-continuous-delivery/7u-container-images/tree/main/images/u/alpine/terraform
    image: iwcd-az-cli-dev-u:azure-linux
    container_name: iwcd-sbx-mft-azure-cli
    hostname: iwcd-sbx-mft-azure-cli
    read_only: true
    environment:
      #- ARM_CLIENT_ID
      #- ARM_CLIENT_SECRET
      - ARM_TENANT_ID
      - ARM_SUBSCRIPTION_ID
      # Default position for the kubeconfig
      - KUBECONFIG=/azcli/config/.kube/config-mft
    volumes:
      - ../..:/azcli
      - iwcd-mft-az-cli-home:/home/iwcd-az-cli-dev/ # iwcd-tf fixed in the prerequisite image
      - tmp:/tmp/
    # Ports - in case proxying with kubectl
    # Default IS ports
    ports:
      - 5555:5555
      - 5556:5556
      # LB SFTP
      - 50022:50022
      # Node 1 SFTP
      - 51022:51022
      # Node 2 SFTP
      - 52022:52022
      # Node 1 IS HTTP + HTTPS
      - 51055:51055
      - 51056:51056
      # Node 2 IS HTTP + HTTPS
      - 52055:52055
      - 52056:52056
    entrypoint: sleep infinity

volumes:
  iwcd-mft-az-cli-home:
  tmp: